name = "Jenks"
uuid = "ea09bcba-b530-11e9-285d-9b3245f059b3"
authors = ["milankl"]
version = "0.1.0"

[compat]
julia = "1"
StatsBase = "0.30"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
